export const studentType ={
    FETCH_STUDENT_REQUEST:"FETCH_STUDENT_REQUEST",
    FETCH_STUDENT_SUCCESS:"FETCH_STUDENT_SUCCESS",
    FETCH_STUDENT_FAILURE:"FETCH_STUDENT_FAILURE",

    FETCH_STUDENTS_REQUEST:"FETCH_STUDENTS_REQUEST",
    FETCH_STUDENTS_SUCCESS:"FETCH_STUDENTS_SUCCESS",
    FETCH_STUDENTS_FAILURE:"FETCH_STUDENTS_FAILURE",

    CREATE_STUDENT_REQUEST:"CREATE_STUDENT_REQUEST",
    CREATE_STUDENT_SUCCESS:"CREATE_STUDENT_SUCCESS",
    CREATE_STUDENT_FAILURE:"CREATE_STUDENT_FAILURE",

    UPDATE_STUDENT_REQUEST:"UPDATE_STUDENT_REQUEST",
    UPDATE_STUDENT_SUCCESS:"UPDATE_STUDENT_SUCCESS",
    UPDATE_STUDENT_FAILURE:"UPDATE_STUDENT_FAILURE",

    DELETE_STUDENT_REQUEST:"DELETE_STUDENT_REQUEST",
    DELETE_STUDENT_SUCCESS:"DELETE_STUDENT_SUCCESS",
    DELETE_STUDENT_FAILURE:"DELETE_STUDENT_FAILURE",

    RESET_STUDENT:"RESET_STUDENT",  
}